title: Cálculo Numérico y Programación
author: Departamento de Matemática Aplicada

only_build_toc_files: true

execute:
  execute_notebooks: force
  timeout: 1000
  allow_errors: true

latex:
  latex_documents:
    targetname: book.tex

parse:
  myst_enable_extensions:
    - html_image
    - dollarmath
    - amsmath
    - colon_fence

html:
  favicon: images/EscUpm.jpg
  logo: images/LOGOTIPOcolorPNG.png

bibtex_bibfiles:
  - ./content/cnpBibtex.bib

sphinx:
  config:
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    bibtex_reference_style: author_year
    use_multitoc_numbering: true
  extra_extensions:
    - sphinx_proof

repository:
  url: "https://github.com/dma-etsiaab-upm/jbookCNP"
  branch: master
  path_to_book: ""

launch_buttons:
  binderhub_url: "https://mybinder.org"
  notebook_interface: "classic"
  colab_url: "https://colab.research.google.com"

